### ISSUE TITLE
Vendor file download not working

### ISSUE THREAD

**Issue by 5amuraix** [J-A-M-E-5/heroku16-buildpack-python-opencv-dlib#1]
Hello,

I tried to deploy this buildpack on Heroku, but there is a problem with downloading the vendor file from the current location:     http://chunk.io/f/1258a029ba374aa590a819154e0000a3

Also, when pushing my app, Heroku displays an error saying the pip3 command is not found? 

Thank you

**Comment by J-A-M-E-5** [comment]
These have become a bit stale. I'm too busy with paid work these days I'm afraid.
